version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    networks:
      - app_network


  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge